name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  tests_2015:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run tests 2015
        working-directory: ./2015
        run: cargo test --verbose

  tests_2020:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run tests 2020
        working-directory: ./2020
        run: cargo test --verbose

  tests_2022:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run tests 2022
        working-directory: ./2022
        run: cargo test --verbose

  tests_2023:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run tests 2023
        working-directory: ./2023
        run: cargo test --verbose
