name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests 2015
      working-directory: ./2015
      run: cargo test --verbose
    - name: Run tests 2020
      working-directory: ./2020
      run: cargo test --verbose
